#!/usr/bin/env bash

cmd_help() {
    echo "Lazy Pacman $VERSION - command reference"
    echo ""
    echo "  Package management"
    printf "  %-22s %-34s %s\n" "install <pkg...>"   "Install one or more packages"       "-> $PKG_W -S <pkg...>"
    printf "  %-22s %-34s %s\n" "remove <pkg...>"    "Remove package + orphan deps"        "-> $PKG_W -Rs <pkg...>"
    printf "  %-22s %-34s %s\n" "purge <pkg...>"     "Remove package + config files"       "-> $PKG_W -Rns <pkg...>"
    printf "  %-22s %-34s %s\n" "update"             "Sync repositories"                   "-> $PKG_W -Sy"
    printf "  %-22s %-34s %s\n" "upgrade"            "Upgrade all packages"                "-> $PKG_W -Syu"
    printf "  %-22s %-34s %s\n" "safe-upgrade"       "Upgrade + log + pacnew check"        "-> $PKG_W -Syu + log"
    printf "  %-22s %-34s %s\n" "downgrade <pkg>"    "Install a cached older version"       "-> sudo pacman -U <file>"
    echo ""
    echo "  Upgrade control"
    printf "  %-22s %-34s %s\n" "ignore <pkg...>"     "Pin package(s) - skip on upgrade"    "-> /etc/pacman.conf IgnorePkg"
    printf "  %-22s %-34s %s\n" "unignore <pkg...>"  "Unpin package(s) - allow upgrades"   "-> /etc/pacman.conf IgnorePkg"
    echo ""
    echo "  Updates"
    printf "  %-22s %-34s %s\n" "check-updates"      "List available updates (no install)" "-> checkupdates / $PKG -Qu"
    echo ""
    echo "  Query"
    printf "  %-22s %-34s %s\n" "search <term>"      "Search for a package"                "-> $PKG -Ss <term>"
    printf "  %-22s %-34s %s\n" "info <pkg>"         "Show package details"                "-> $PKG -Si <pkg>"
    printf "  %-22s %-34s %s\n" "list"               "List installed (names only)"         "-> $PKG -Qq"
    printf "  %-22s %-34s %s\n" "installed"          "List installed (names+versions)"     "-> $PKG -Q"
    printf "  %-22s %-34s %s\n" "check <pkg...>"     "Check if package(s) are installed"  "-> $PKG -Q <pkg>"
    printf "  %-22s %-34s %s\n" "deps <pkg>"         "Show package dependency tree"        "-> pactree <pkg>"
    printf "  %-22s %-34s %s\n" "orphans"            "List orphan packages"                "-> $PKG -Qdt"
    echo ""
    echo "  Pacnew / pacsave"
    printf "  %-22s %-34s %s\n" "pacnew"             "Find .pacnew/.pacsave files"         "-> find /etc -name *.pacnew"
    echo ""
    echo "  Logs"
    printf "  %-22s %-34s %s\n" "log"                "List upgrade logs"                   "-> ls $LOG_DIR"
    printf "  %-22s %-34s %s\n" "log <file>"         "Read a log file"                     "-> less $LOG_DIR/<file>"
    printf "  %-22s %-34s %s\n" "logclean"           "Remove all upgrade logs"             "-> rm $LOG_DIR/*.log"
    echo ""
    echo "  Cleanup"
    printf "  %-22s %-34s %s\n" "remove-orphans"     "Remove all orphan packages"          "-> $PKG_W -Rns \$($PKG -Qdtq)"
    printf "  %-22s %-34s %s\n" "cache-size"         "Show package cache size"             "-> du -sh /var/cache/pacman/pkg/"
    printf "  %-22s %-34s %s\n" "cache-clean"        "Keep only latest version per pkg"    "-> sudo pacman -Sc"
    printf "  %-22s %-34s %s\n" "cache-clean-old"    "Remove cache of uninstalled pkgs"    "-> sudo paccache -ruk0"
    printf "  %-22s %-34s %s\n" "cache-clean-all"    "Remove the entire package cache"     "-> sudo pacman -Scc"
    echo ""
    echo "Tip: multiple packages and extra flags are passed through directly."
    echo "     lazypac install firefox chromium --noconfirm"
    echo "     lazypac upgrade --devel"
    echo "     lazypac safe-upgrade --ignore hyprland"
}
